# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eacad0a49701769af3c356562369e93a03fb147935f79848a915489e27eef14c62a397e032bbf6eee49047ba09d23b2f0532b699f9a9682fbc5604ed7c60014c

test:
  secret_key_base: 3f4e222127e5d8e70cecccff6bfba1def2a57926bdb1ed80cbc7fe7fa8e53a40bce49b86ce67e10cb979c0b32b41935d78d5fcc0d0f06d14ef4ea6dae3410bb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
